package com.besson.arknights.datagen;

import com.besson.arknights.block.ModBlocks;
import com.besson.arknights.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class ModEnUsLangProvider extends FabricLanguageProvider {
    public static final String painting = "painting.arknights-furniture.";
    public ModEnUsLangProvider(FabricDataOutput dataOutput) {
        super(dataOutput, "en_us");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModItems.ABYSSAL_HUNTERS_LOGO, "Abyssal Hunters Logo");
        translationBuilder.add(ModItems.AEGIR_LOGO, "Aegir Logo");
        translationBuilder.add(ModItems.BABEL_LOGO, "Babel Logo");
        translationBuilder.add(ModItems.BLACK_STEEL_LOGO, "Black Steel Logo");
        translationBuilder.add(ModItems.BOLIVAR_LOGO, "Bolivar Logo");
        translationBuilder.add(ModItems.COLUMBIA_LOGO, "Columbia Logo");
        translationBuilder.add(ModItems.DONG_LOGO, "Dong Logo");
        translationBuilder.add(ModItems.DUBLINN_LOGO, "Dublinn Logo");
        translationBuilder.add(ModItems.ELITE_OP_LOGO, "Elite Op Logo");
        translationBuilder.add(ModItems.FOLLOWERS_LOGO, "Followers Logo");
        translationBuilder.add(ModItems.GLASGOW_LOGO, "Glasgow Logo");
        translationBuilder.add(ModItems.IBERIA_LOGO, "Iberia Logo");
        translationBuilder.add(ModItems.KARLAN_TRADE_LOGO, "Karlan Trade Logo");
        translationBuilder.add(ModItems.KAZIMIERZ_LOGO, "Kazimierz Logo");
        translationBuilder.add(ModItems.KJERAG_LOGO, "Kjerag Logo");
        translationBuilder.add(ModItems.LATERANO_LOGO, "Laterano Logo");
        translationBuilder.add(ModItems.LEES_DETECTIVE_AGENCY_LOGO, "Lee's Detective Agency Logo");
        translationBuilder.add(ModItems.LEITHANIEN_LOGO, "Leithanien Logo");
        translationBuilder.add(ModItems.LUNGMEN_GUARD_DEPARTMENT_LOGO, "Lungmen Guard Department Logo");
        translationBuilder.add(ModItems.LUNGMEN_LOGO, "Lungmen Logo");
        translationBuilder.add(ModItems.MINOS_LOGO, "Minos Logo");
        translationBuilder.add(ModItems.OP_A4_LOGO, "Op A4 Logo");
        translationBuilder.add(ModItems.OP_RESERVE_A1_LOGO, "Op Reserve A1 Logo");
        translationBuilder.add(ModItems.OP_RESERVE_A4_LOGO, "Op Reserve A4 Logo");
        translationBuilder.add(ModItems.OP_RESERVE_A6_LOGO, "Op Reserve A6 Logo");
        translationBuilder.add(ModItems.PENGUIN_LOGISTICS_LOGO, "Penguin Logistics Logo");
        translationBuilder.add(ModItems.PINUS_SYLVESTRIS_LOGO, "Pinus Sylvestris Logo");
        translationBuilder.add(ModItems.RHINE_LAB_LOGO, "Rhine Lab Logo");
        translationBuilder.add(ModItems.RHODES_ISLAND_LOGO, "Rhodes Island Logo");
        translationBuilder.add(ModItems.RHODES_ISLAND_OVERRIDE_LOGO, "Rhodes Island Override Logo");
        translationBuilder.add(ModItems.RIM_BILLITON_LOGO, "Rim Billiton Logo");
        translationBuilder.add(ModItems.SAMI_LOGO, "Sami Logo");
        translationBuilder.add(ModItems.SARGON_LOGO, "Sargon Logo");
        translationBuilder.add(ModItems.SIESTA_LOGO, "Siesta Logo");
        translationBuilder.add(ModItems.SIRACUSA_BRANCHES_LOGO, "Siracusa Branches Logo");
        translationBuilder.add(ModItems.SIRACUSA_LOGO, "Siracusa Logo");
        translationBuilder.add(ModItems.SUI_LOGO, "Sui Logo");
        translationBuilder.add(ModItems.SWEEP_LOGO, "S.W.E.E.P Logo");
        translationBuilder.add(ModItems.TEAM_RAINBOW_LOGO, "Team Rainbow Logo");
        translationBuilder.add(ModItems.URSUS_LOGO, "Ursus Logo");
        translationBuilder.add(ModItems.URSUS_STUDENT_SELF_GOVERNING_GROUP_LOGO, "Ursus Student Self-Governing Group Logo");
        translationBuilder.add(ModItems.VICTORIA_LOGO, "Victoria Logo");
        translationBuilder.add(ModItems.YAN_LOGO, "Yan Logo");

        translationBuilder.add(painting + "abyssal_hunters.title", "Abyssal Hunters");
        translationBuilder.add(painting + "abyssal_hunters.author", "Hypergryph");
        translationBuilder.add(painting + "aegir.title", "Aegir");
        translationBuilder.add(painting + "aegir.author", "Hypergryph");
        translationBuilder.add(painting + "babel.title", "Babel");
        translationBuilder.add(painting + "babel.author", "Hypergryph");
        translationBuilder.add(painting + "black_steel.title", "Black Steel");
        translationBuilder.add(painting + "black_steel.author", "Hypergryph");
        translationBuilder.add(painting + "bolivar.title", "Bolivar");
        translationBuilder.add(painting + "bolivar.author", "Hypergryph");
        translationBuilder.add(painting + "columbia.title", "Columbia");
        translationBuilder.add(painting + "columbia.author", "Hypergryph");
        translationBuilder.add(painting + "dong.title", "Dong");
        translationBuilder.add(painting + "dong.author", "Hypergryph");
        translationBuilder.add(painting + "dublinn.title", "Dublinn");
        translationBuilder.add(painting + "dublinn.author", "Hypergryph");
        translationBuilder.add(painting + "elite_op.title", "Elite Op");
        translationBuilder.add(painting + "elite_op.author", "Hypergryph");
        translationBuilder.add(painting + "followers.title", "Followers");
        translationBuilder.add(painting + "followers.author", "Hypergryph");
        translationBuilder.add(painting + "glasgow.title", "Glasgow");
        translationBuilder.add(painting + "glasgow.author", "Hypergryph");
        translationBuilder.add(painting + "iberia.title", "Iberia");
        translationBuilder.add(painting + "iberia.author", "Hypergryph");
        translationBuilder.add(painting + "karlan_trade.title", "Karlan Trade");
        translationBuilder.add(painting + "karlan_trade.author", "Hypergryph");
        translationBuilder.add(painting + "kazimierz.title", "Kazimierz");
        translationBuilder.add(painting + "kazimierz.author", "Hypergryph");
        translationBuilder.add(painting + "kjerag.title", "Kjerag");
        translationBuilder.add(painting + "kjerag.author", "Hypergryph");
        translationBuilder.add(painting + "laterano.title", "Laterano");
        translationBuilder.add(painting + "laterano.author", "Hypergryph");
        translationBuilder.add(painting + "lee-s_detective_agency.title", "Lee's Detective Agency");
        translationBuilder.add(painting + "lee-s_detective_agency.author", "Hypergryph");
        translationBuilder.add(painting + "leithanien.title", "Leithanien");
        translationBuilder.add(painting + "leithanien.author", "Hypergryph");
        translationBuilder.add(painting + "lungmen_guard_department.title", "Lungmen Guard Department");
        translationBuilder.add(painting + "lungmen_guard_department.author", "Hypergryph");
        translationBuilder.add(painting + "lungmen.title", "Lungmen");
        translationBuilder.add(painting + "lungmen.author", "Hypergryph");
        translationBuilder.add(painting + "minos.title", "Minos");
        translationBuilder.add(painting + "minos.author", "Hypergryph");
        translationBuilder.add(painting + "op_a4.title", "Op A4");
        translationBuilder.add(painting + "op_a4.author", "Hypergryph");
        translationBuilder.add(painting + "op_reserve_a1.title", "Op Reserve A1");
        translationBuilder.add(painting + "op_reserve_a1.author", "Hypergryph");
        translationBuilder.add(painting + "op_reserve_a4.title", "Op Reserve A4");
        translationBuilder.add(painting + "op_reserve_a4.author", "Hypergryph");
        translationBuilder.add(painting + "op_reserve_a6.title", "Op Reserve A6");
        translationBuilder.add(painting + "op_reserve_a6.author", "Hypergryph");
        translationBuilder.add(painting + "penguin_logistics.title", "Penguin Logistics");
        translationBuilder.add(painting + "penguin_logistics.author", "Hypergryph");
        translationBuilder.add(painting + "pinus_sylvestris.title", "Pinus Sylvestris");
        translationBuilder.add(painting + "pinus_sylvestris.author", "Hypergryph");
        translationBuilder.add(painting + "rhine_lab.title", "Rhine Lab");
        translationBuilder.add(painting + "rhine_lab.author", "Hypergryph");
        translationBuilder.add(painting + "rhodes_island.title", "Rhodes Island");
        translationBuilder.add(painting + "rhodes_island.author", "Hypergryph");
        translationBuilder.add(painting + "rhodes_island_override.title", "Rhodes Island Override");
        translationBuilder.add(painting + "rhodes_island_override.author", "Hypergryph");
        translationBuilder.add(painting + "rim_billiton.title", "Rim Billiton");
        translationBuilder.add(painting + "rim_billiton.author", "Hypergryph");
        translationBuilder.add(painting + "sami.title", "Sami");
        translationBuilder.add(painting + "sami.author", "Hypergryph");
        translationBuilder.add(painting + "sargon.title", "Sargon");
        translationBuilder.add(painting + "sargon.author", "Hypergryph");
        translationBuilder.add(painting + "siesta.title", "Siesta");
        translationBuilder.add(painting + "siesta.author", "Hypergryph");
        translationBuilder.add(painting + "siracusa_branches.title", "Siracusa Branches");
        translationBuilder.add(painting + "siracusa_branches.author", "Hypergryph");
        translationBuilder.add(painting + "siracusa.title", "Siracusa");
        translationBuilder.add(painting + "siracusa.author", "Hypergryph");
        translationBuilder.add(painting + "sui.title", "Sui");
        translationBuilder.add(painting + "sui.author", "Hypergryph");
        translationBuilder.add(painting + "sweep.title", "Sweep");
        translationBuilder.add(painting + "sweep.author", "Hypergryph");
        translationBuilder.add(painting + "team_rainbow.title", "Team Rainbow");
        translationBuilder.add(painting + "team_rainbow.author", "Hypergryph");
        translationBuilder.add(painting + "ursus.title", "Ursus");
        translationBuilder.add(painting + "ursus.author", "Hypergryph");
        translationBuilder.add(painting + "ursus_student_self-governing_group.title", "Ursus Student Self-Governing Group");
        translationBuilder.add(painting + "ursus_student_self-governing_group.author", "Hypergryph");
        translationBuilder.add(painting + "victoria.title", "Victoria");
        translationBuilder.add(painting + "victoria.author", "Hypergryph");
        translationBuilder.add(painting + "yan.title", "Yan");
        translationBuilder.add(painting + "yan.author", "Hypergryph");
        translationBuilder.add(painting + "unknown_bones.title", "Unknown Bones");
        translationBuilder.add(painting + "unknown_bones.author", "Hypergryph");
        translationBuilder.add(painting + "unknown_specimen1.title", "Unknown Specimen 1");
        translationBuilder.add(painting + "unknown_specimen1.author", "Hypergryph");
        translationBuilder.add(painting + "unknown_specimen2.title", "Unknown Specimen 2");
        translationBuilder.add(painting + "unknown_specimen2.author", "Hypergryph");
        translationBuilder.add(painting + "unknown_specimen3.title", "Unknown Specimen 3");
        translationBuilder.add(painting + "unknown_specimen3.author", "Hypergryph");
        translationBuilder.add(painting + "painting_with_sandalwood_frame.title", "Painting With Sandalwood Frame");
        translationBuilder.add(painting + "painting_with_sandalwood_frame.author", "Hypergryph");
        translationBuilder.add(painting + "painting_with_teak_frame.title", "Painting With Teak Frame");
        translationBuilder.add(painting + "painting_with_teak_frame.author", "Hypergryph");
        translationBuilder.add(painting + "pizzeria_decorative_painting.title", "Pizzeria Decorative Painting");
        translationBuilder.add(painting + "pizzeria_decorative_painting.author", "Hypergryph");
        translationBuilder.add(painting + "stream_of_consciousness_painting.title", "Stream Of Consciousness Painting");
        translationBuilder.add(painting + "stream_of_consciousness_painting.author", "Hypergryph");
        translationBuilder.add(painting + "the_golden_era.title", "The Golden Era");
        translationBuilder.add(painting + "the_golden_era.author", "Hypergryph");
        translationBuilder.add(painting + "voyage_impression_kids_painting", "Voyage Impression Kids Painting");
        translationBuilder.add(painting + "voyage_impression_kids_painting.author", "Hypergryph");
        translationBuilder.add(painting + "band_promotional_poster", "Band Promotional Poster");
        translationBuilder.add(painting + "band_promotional_poster.author", "Hypergryph");
        translationBuilder.add(painting + "sarkaz_rock_n_roll_poster", "Sarkaz Rock 'n' Roll Poster");
        translationBuilder.add(painting + "sarkaz_rock_n_roll_poster.author", "Hypergryph");
        translationBuilder.add(painting + "scenery_from_reimselar", "Scenery From Reimselar");
        translationBuilder.add(painting + "scenery_from_reimselar.author", "Hypergryph");

        translationBuilder.add(ModItems.FURN_PARTS, "Furn Parts");
        translationBuilder.add(ModItems.CARDBOARD, "Cardboard");
        translationBuilder.add(ModItems.FURN_PARTS_ZIP1, "Furn Parts Zip 1");
        translationBuilder.add(ModItems.FURN_PARTS_ZIP2, "Furn Parts Zip 2");

        translationBuilder.add(ModBlocks.AIR_MATTRESS, "Air Mattress");
        translationBuilder.add(ModBlocks.ATTENDANCE_BOARD, "Attendance Board");
        translationBuilder.add(ModBlocks.CARGO_TROLLEY, "Cargo Trolley");
        translationBuilder.add(ModBlocks.CARTON, "Carton");
        translationBuilder.add(ModBlocks.CARTON_STOOL, "Carton Stool");
        translationBuilder.add(ModBlocks.GRAFFITI, "Graffiti");
        translationBuilder.add(ModBlocks.LARGE_SHELF1, "Large Shelf 1");
        translationBuilder.add(ModBlocks.LARGE_SHELF2, "Large Shelf 2");
        translationBuilder.add(ModBlocks.LARGE_SHELF3, "Large Shelf 3");
        translationBuilder.add(ModBlocks.LARGE_SHELF4, "Large Shelf 4");
        translationBuilder.add(ModBlocks.PALLET, "Pallet");
        translationBuilder.add(ModBlocks.PILE_OF_CARTONS, "Pile Of Cartons");
        translationBuilder.add(ModBlocks.PORTABLE_CALCULATOR, "Portable Calculator");
        translationBuilder.add(ModBlocks.POST_IT_NOTE, "Post It Note");

        translationBuilder.add(ModBlocks.GRAYISH_WALL_LIGHT, "Grayish Wall Light");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_CLOCK, "Simple Black Clock");
        translationBuilder.add(ModBlocks.BLACK_HD_TV, "Black HD TV");
        translationBuilder.add(ModBlocks.BLACK_NIGHTSTAND, "Black Nightstand");
        translationBuilder.add(ModBlocks.BLACK_BED, "Black Bed");
        translationBuilder.add(ModBlocks.SMALL_CALLBOARD, "Small Callboard");
        translationBuilder.add(ModBlocks.BLACK_AND_WHITE_SQUARE_TABLE, "Black And White Square Table");
        translationBuilder.add(ModBlocks.LOW_BLACK_AND_WHITE_SOFA, "Low Black And White Sofa");
        translationBuilder.add(ModBlocks.CHECKERBOARD_BOOKCASE1, "Checkerboard Bookcase 1");
        translationBuilder.add(ModBlocks.CHECKERBOARD_BOOKCASE2, "Checkerboard Bookcase 2");
        translationBuilder.add(ModBlocks.CHECKERBOARD_BOOKCASE3, "Checkerboard Bookcase 3");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_CABINET, "Simple Black Cabinet");
        translationBuilder.add(ModBlocks.BLACK_OFFICE_CHAIR, "Black Office Chair");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_DESK_LEFT, "Simple Black Desk Left");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_DESK_RIGHT, "Simple Black Desk Right");

        translationBuilder.add(ModBlocks.ORANGE_WALL_LAMP, "Orange Wall Lamp");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_CLOCK, "Simple Orange Clock");
        translationBuilder.add(ModBlocks.ORANGE_HD_TV, "Orange HD TV");
        translationBuilder.add(ModBlocks.ORANGE_NIGHTSTAND, "Orange Nightstand");
        translationBuilder.add(ModBlocks.ORANGE_BED, "Orange Bed");
        translationBuilder.add(ModBlocks.SMALL_NOTICEBOARD, "Small Noticeboard");
        translationBuilder.add(ModBlocks.ORANGE_SQUARE_TABLE, "Orange Square Table");
        translationBuilder.add(ModBlocks.LOW_ORANGE_SOFA, "Low Orange Sofa");
        translationBuilder.add(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE1, "Orange Checkerboard Bookcase 1");
        translationBuilder.add(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE2, "Orange Checkerboard Bookcase 2");
        translationBuilder.add(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE3, "Orange Checkerboard Bookcase 3");
        translationBuilder.add(ModBlocks.ORANGE_SWIVEL_CHAIR, "Orange Swivel Chair");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_CABINET, "Simple Orange Cabinet");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_DESK_LEFT, "Simple Orange Desk Left");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_DESK_RIGHT, "Simple Orange Desk Right");

        translationBuilder.add(ModBlocks.BROWN_BEAN_BAG_SOFA, "Brown Bean Bag Sofa");
        translationBuilder.add(ModBlocks.ECO_EXHIBITION_CABINET, "Eco Exhibition Cabinet");
        translationBuilder.add(ModBlocks.ECO_EXHIBITION_CABINET_BASE, "Eco Exhibition Cabinet Base");
        translationBuilder.add(ModBlocks.FLUSH_MOUNT_RECTANGLE_CEILING_LIGHT, "Flush Mount Rectangle Ceiling Light");
        translationBuilder.add(ModBlocks.FLUSH_MOUNT_SQUARE_CEILING_LIGHT, "Flush Mount Square Ceiling Light");
        translationBuilder.add(ModBlocks.METALLIC_BED, "Metallic Bed");
        translationBuilder.add(ModBlocks.POTTED_BROADLEAF_PLANT, "Potted Broadleaf Plant");
        translationBuilder.add(ModBlocks.POTTED_CONIFER_PLANT, "Potted Conifer Plant");
        translationBuilder.add(ModBlocks.POTTED_SUCCULENT_PLANT, "Potted Succulent Plant");
        translationBuilder.add(ModBlocks.SMALL_SQUARE_NIGHTSTAND, "Small Square Nightstand");
        translationBuilder.add(ModBlocks.SPECIMEN_DATA_BOARD, "Specimen Data Board");
        translationBuilder.add(ModBlocks.WIRE_SIDE_TABLE, "Wire Side Table");

        translationBuilder.add(ModBlocks.ANTI_EXPLOSION_TRASH_CAN, "Anti-Explosion Trash Can");
        translationBuilder.add(ModBlocks.BUILT_IN_FILE_CABINET1, "Built-In File Cabinet 1");
        translationBuilder.add(ModBlocks.BUILT_IN_FILE_CABINET2, "Built-In File Cabinet 2");
        translationBuilder.add(ModBlocks.BUNK_BED_IN_CABIN, "Bunk Bed In Cabin");
        translationBuilder.add(ModBlocks.CABIN_FIRE_EXTINGUISHER_KIT, "Cabin Fire Extinguisher Kit");
        translationBuilder.add(ModBlocks.CABIN_FLUSH_MOUNT_PIPE, "Cabin Flush Mount Pipe");
        translationBuilder.add(ModBlocks.CONTROL_DISPLAY, "Control Display");
        translationBuilder.add(ModBlocks.DIY_SWIVEL_CHAIR, "DIY Swivel Chair");
        translationBuilder.add(ModBlocks.DIY_WORKBENCH_LEFT, "DIY Workbench Left");
        translationBuilder.add(ModBlocks.DIY_WORKBENCH_RIGHT, "DIY Workbench Right");
        translationBuilder.add(ModBlocks.GENERAL_CONSOLE, "General Console");
        translationBuilder.add(ModBlocks.NOTE_BOARD_IN_CABIN, "Note Board In Cabin");

        translationBuilder.add(ModBlocks.BAR_CEILING, "Bar Ceiling");
        translationBuilder.add(ModBlocks.BARSTOOL_WITH_CURVED_LEGS, "Barstool With Curved Legs");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_COFFEE1, "Beverage Cabinet Coffee 1");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_COFFEE2, "Beverage Cabinet Coffee 2");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_DC, "Beverage Cabinet DC");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_DRINK, "Beverage Cabinet Drink");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_EMPTY, "Beverage Cabinet Empty");
        translationBuilder.add(ModBlocks.BEVERAGE_MENU, "Beverage Menu");
        translationBuilder.add(ModBlocks.BOLIVARIAN_COFFEE_BEAN, "Bolivarian Coffee Bean");
        translationBuilder.add(ModBlocks.BROWN_BOOKCASE1, "Brown Bookcase 1");
        translationBuilder.add(ModBlocks.BROWN_BOOKCASE2, "Brown Bookcase 2");
        translationBuilder.add(ModBlocks.BROWN_BOOKCASE3, "Brown Bookcase 3");
        translationBuilder.add(ModBlocks.COLUMBIAN_STREET_VIEW_PHOTO, "Columbian Street View Photo");
        translationBuilder.add(ModBlocks.DINING_CHAIR, "Dining Chair");
        translationBuilder.add(ModBlocks.PEDESTAL_COFFEE_TABLE, "Pedestal Coffee Table");
        translationBuilder.add(ModBlocks.PENDANT_LIGHT, "Pendant Light");
        translationBuilder.add(ModBlocks.POTTED_LONG_LEAF_PLANT, "Potted Long Leaf Plant");
        translationBuilder.add(ModBlocks.RED_BRICK_CAFE_BAR, "Red Brick Cafe Bar");
        translationBuilder.add(ModBlocks.RED_BROWN_CABINET, "Red Brown Cabinet");
        translationBuilder.add(ModBlocks.SOFT_CEILING_LIGHT, "Soft Ceiling Light");

        translationBuilder.add(ModBlocks.BLACK_PEDESTAL_TABLE, "Black Pedestal Table");
        translationBuilder.add(ModBlocks.BLACK_VINTAGE_CHAIR, "Black Vintage Chair");
        translationBuilder.add(ModBlocks.BLACK_VINTAGE_STOOL, "Black Vintage Stool");
        translationBuilder.add(ModBlocks.BRIGHT_WALL_LIGHT, "Bright Wall Light");
        translationBuilder.add(ModBlocks.DUPLEX_WOODEN_FENCE, "Duplex Wooden Fence");
        translationBuilder.add(ModBlocks.LOW_SANDALWOOD_MEETING_TABLE, "Low Sandalwood Meeting Table");
        translationBuilder.add(ModBlocks.SANDALWOOD_BED, "Sandalwood Bed");
        translationBuilder.add(ModBlocks.SANDALWOOD_MEETING_BOARD, "Sandalwood Meeting Board");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_LOUNGE_CHAIR, "Simple Black Lounge Chair");
        translationBuilder.add(ModBlocks.SMALL_SANDALWOOD_NIGHTSTAND, "Small Sandalwood Nightstand");

        translationBuilder.add(ModBlocks.DUPLEX_BRONZE_FENCE, "Duplex Bronze Fence");
        translationBuilder.add(ModBlocks.LOW_TEAK_MEETING_TABLE, "Low Teak Meeting Table");
        translationBuilder.add(ModBlocks.PIANO_BLACK_VINTAGE_CHAIR, "Piano Black Vintage Chair");
        translationBuilder.add(ModBlocks.PIANO_BLACK_VINTAGE_STOOL, "Piano Black Vintage Stool");
        translationBuilder.add(ModBlocks.SIMPLE_GRAY_LOUNGE_CHAIR, "Simple Gray Lounge Chair");
        translationBuilder.add(ModBlocks.SMALL_TEAK_NIGHTSTAND, "Small Teak Nightstand");
        translationBuilder.add(ModBlocks.TEAK_BED, "Teak Bed");
        translationBuilder.add(ModBlocks.TEAK_ATTENDANCE_BOARD, "Teak Attendance Board");
        translationBuilder.add(ModBlocks.WHITE_PEDESTAL_TABLE, "White Pedestal Table");

        translationBuilder.add(ModBlocks.CREATURES_REMAINS, "Creature's Remains");
        translationBuilder.add(ModBlocks.FUTON_BUNK_BED_BOTTOM, "Futon Bunk Bed Bottom");
        translationBuilder.add(ModBlocks.FUTON_BUNK_BED_TOP, "Futon Bunk Bed Top");
        translationBuilder.add(ModBlocks.HANDMADE_WOOD_BASKET, "Handmade Wood Basket");
        translationBuilder.add(ModBlocks.LOG_BEAM, "Log Beam");
        translationBuilder.add(ModBlocks.LOG_CABINET_BOTTOM, "Log Cabinet Bottom");
        translationBuilder.add(ModBlocks.LOG_CABINET_TOP1, "Log Cabinet Top 1");
        translationBuilder.add(ModBlocks.LOG_CABINET_TOP2, "Log Cabinet Top 2");
        translationBuilder.add(ModBlocks.LOG_DINING_CHAIR, "Log Dining Chair");
        translationBuilder.add(ModBlocks.LOG_DINING_TABLE, "Log Dining Table");
        translationBuilder.add(ModBlocks.ROCKING_CHAIR_WITH_CUSHION, "Rocking Chair With Cushion");
        translationBuilder.add(ModBlocks.SPRUCE_WOOD_VIOLIN, "Spruce Wood Violin");
        translationBuilder.add(ModBlocks.VINTAGE_CEILING_FAN, "Vintage Ceiling Fan");
        translationBuilder.add(ModBlocks.VINTAGE_CEILING_LIGHT, "Vintage Ceiling Light");

        translationBuilder.add(ModBlocks.DINING_PLATE, "Dining Plate");
        translationBuilder.add(ModBlocks.PIZZA_BOWL, "Pizza Bowl");
        translationBuilder.add(ModBlocks.PIZZA_BOX, "Pizza Box");
        translationBuilder.add(ModBlocks.PIZZA_MENU1, "Pizza Menu 1");
        translationBuilder.add(ModBlocks.PIZZA_MENU2, "Pizza Menu 2");
        translationBuilder.add(ModBlocks.PIZZERIA_BLACK_COUNTER, "Pizzeria Black Counter");
        translationBuilder.add(ModBlocks.PIZZERIA_CUPBOARD, "Pizzeria Cupboard");
        translationBuilder.add(ModBlocks.PIZZERIA_EXIT_SIGN, "Pizzeria Exit Sign");
        translationBuilder.add(ModBlocks.PIZZERIA_DINING_CHAIR, "Pizzeria Dining Chair");
        translationBuilder.add(ModBlocks.PIZZERIA_HIGH_STOOL, "Pizzeria High Stool");
        translationBuilder.add(ModBlocks.PIZZERIA_MOVEABLE_TABLE, "Pizzeria Moveable Table");
        translationBuilder.add(ModBlocks.PIZZERIA_PLATE_RACK, "Pizzeria Plate Rack");
        translationBuilder.add(ModBlocks.PIZZERIA_POSTER_COLUMN, "Pizzeria Poster Column");
        translationBuilder.add(ModBlocks.PIZZERIA_POSTER_STAND, "Pizzeria Poster Stand");
        translationBuilder.add(ModBlocks.PIZZERIA_SOFT_CEILING_LIGHT, "Pizzeria Soft Ceiling Light");

        translationBuilder.add(ModBlocks.BARSTOOL, "Barstool");
        translationBuilder.add(ModBlocks.BILLBOARD_JUKEBOX, "Billboard Jukebox");
        translationBuilder.add(ModBlocks.BLACK_AND_GOLDEN_FREEZER, "Black And Golden Freezer");
        translationBuilder.add(ModBlocks.MODERN_HOTEL_CEILING_LIGHT, "Modern Hotel Ceiling Light");
        translationBuilder.add(ModBlocks.MODERN_HOTEL_CHANDELIER, "Modern Hotel Chandelier");
        translationBuilder.add(ModBlocks.MODERN_HOTEL_FLOOR_LAMP, "Modern Hotel Floor Lamp");
        translationBuilder.add(ModBlocks.MODERN_HOTEL_SOFA, "Modern Hotel Sofa");
        translationBuilder.add(ModBlocks.MODERN_HOTEL_TABLE, "Modern Hotel Table");
        translationBuilder.add(ModBlocks.MODERN_HOTEL_WALL_LAMP, "Modern Hotel Wall Lamp");
        translationBuilder.add(ModBlocks.MODERN_WALL_DECORATION, "Modern Wall Decoration");
        translationBuilder.add(ModBlocks.MOUNTED_BAR_CEILING1, "Mounted Bar Ceiling 1");
        translationBuilder.add(ModBlocks.MOUNTED_BAR_CEILING2, "Mounted Bar Ceiling 2");
        translationBuilder.add(ModBlocks.VERSATILE_BAR_STAND, "Versatile Bar Stand");
        translationBuilder.add(ModBlocks.WILLIAMS_GRAND_PIANO_SET, "Williams Grand Piano Set");

        translationBuilder.add(ModBlocks.CHENS_CERTIFICATE_OF_HONOR, "Ch'en's Certificate Of Honor");
        translationBuilder.add(ModBlocks.CHENS_CHAIR, "Ch'en's Chair");
        translationBuilder.add(ModBlocks.CHENS_DESK, "Ch'en's Desk");
        translationBuilder.add(ModBlocks.CHENS_WEAPON_RACK, "Ch'en's Weapon Rack");
        translationBuilder.add(ModBlocks.FILE1, "File 1");
        translationBuilder.add(ModBlocks.FILE2, "File 2");
        translationBuilder.add(ModBlocks.LGD_BOOKCASE, "L.D.G. Bookcase");
        translationBuilder.add(ModBlocks.LGD_DAYLIGHT_LIGHT, "L.D.G. Daylight Light");
        translationBuilder.add(ModBlocks.LGD_FLUORESCENT_LIGHT, "L.D.G. Fluorescent Light");
        translationBuilder.add(ModBlocks.LGD_SPECIAL_DUMMY, "L.D.G. Special Dummy");
        translationBuilder.add(ModBlocks.LGD_SPOTLIGHT, "L.D.G. Spotlight");
        translationBuilder.add(ModBlocks.LGD_SUPINE_PLATE, "L.D.G. Supine Plate");
        translationBuilder.add(ModBlocks.LGD_TRASH_CAN, "L.D.G. Trash Can");
        translationBuilder.add(ModBlocks.OFFICE_CLUE_BOARD, "Office Clue Board");
        translationBuilder.add(ModBlocks.POTTED_CACTUS_PLANT, "Potted Cactus Plant");

        translationBuilder.add(ModBlocks.BEACH_HOUSE_FLOOR_LAMP, "Beach House Floor Lamp");
        translationBuilder.add(ModBlocks.BLUE_AND_WHITE_CANVAS_CURTAINS_LEFT, "Blue And White Canvas Curtains Left");
        translationBuilder.add(ModBlocks.BLUE_AND_WHITE_CANVAS_CURTAINS_RIGHT, "Blue And White Canvas Curtains Right");
        translationBuilder.add(ModBlocks.LAZY_BENCH, "Lazy Bench");
        translationBuilder.add(ModBlocks.LAZY_COFFEE_TABLE, "Lazy Coffee Table");
        translationBuilder.add(ModBlocks.LAZY_HIGH_TEA_TABLE, "Lazy High Tea Table");
        translationBuilder.add(ModBlocks.LAZY_LOUNGE_CHAIR, "Lazy Lounge Chair");
        translationBuilder.add(ModBlocks.RHODES_ISLAND_SUMMER_CALENDAR, "Rhodes Island Summer Calendar");
        translationBuilder.add(ModBlocks.SIESTA_COAT_OF_ARMS_SOUVENIR, "Siesta Coat Of Arms Souvenir");
        translationBuilder.add(ModBlocks.SUMMER_BOAT_CABINET_BOTTOM, "Summer Boat Cabinet Bottom");
        translationBuilder.add(ModBlocks.SUMMER_BOAT_CABINET_TOP, "Summer Boat Cabinet Top");
        translationBuilder.add(ModBlocks.SUMMER_COLLECTION_SHELF_CHAIR, "Summer Collection Shelf Chair");
        translationBuilder.add(ModBlocks.SUMMER_COLLECTION_SHELF, "Summer Collection Shelf");
        translationBuilder.add(ModBlocks.SURFBOARD_STAND, "Surfboard Stand");
        translationBuilder.add(ModBlocks.WOODEN_BEAM, "Wooden Beam");

        translationBuilder.add(ModBlocks.AMBER, "Amber");
        translationBuilder.add(ModBlocks.BIRCH, "Birch");
        translationBuilder.add(ModBlocks.DARK_CLOUD, "Dark Cloud");
        translationBuilder.add(ModBlocks.DARK_STEEL, "Dark Steel");
        translationBuilder.add(ModBlocks.DRIFTWOOD, "Driftwood");
        translationBuilder.add(ModBlocks.FLAME, "Flame");
        translationBuilder.add(ModBlocks.GRIT, "Grit");
        translationBuilder.add(ModBlocks.HANGING_SCROLLING_DISPLAY, "Hanging Scrolling Display");
        translationBuilder.add(ModBlocks.REHEARSAL_ROOM_ACCESSORY_SHELF, "Rehearsal Room Accessory Shelf");
        translationBuilder.add(ModBlocks.REHEARSAL_ROOM_BELT_SHELF, "Rehearsal Room Belt Shelf");
        translationBuilder.add(ModBlocks.REHEARSAL_ROOM_BENCH, "Rehearsal Room Bench");
        translationBuilder.add(ModBlocks.REHEARSAL_ROOM_RECEPTION_DESK, "Rehearsal Room Reception Desk");
        translationBuilder.add(ModBlocks.REHEARSAL_ROOM_ROUND_BENCH, "Rehearsal Room Round Bench");
        translationBuilder.add(ModBlocks.REHEARSAL_ROOM_SPOTLIGHT, "Rehearsal Room Spotlight");
        translationBuilder.add(ModBlocks.SHALLOW_SEA, "Shallow Sea");
        translationBuilder.add(ModBlocks.SPOTLIGHT_CEILING, "Spotlight Ceiling");
        translationBuilder.add(ModBlocks.STAGE, "Stage");
        translationBuilder.add(ModBlocks.TOUR_INSTRUMENT_COMBO, "Tour Instrument Combo");
        translationBuilder.add(ModBlocks.WHEAT, "Wheat");
        translationBuilder.add(ModBlocks.YARMAHAN_DRUM_SET, "Yarmahan Drum Set");

        translationBuilder.add(ModBlocks.CLEANROOM_AIRDUCT, "Cleanroom Airduct");
        translationBuilder.add(ModBlocks.CLEANROOM_AIRFLOW_CONTROL_PIPE, "Cleanroom Airflow Control Pipe");
        translationBuilder.add(ModBlocks.CLEANROOM_ANTIMICROBIAL_LAMP, "Cleanroom Antimicrobial Lamp");
        translationBuilder.add(ModBlocks.CLEANROOM_CEILING_LIGHT, "Cleanroom Ceiling Light");
        translationBuilder.add(ModBlocks.CLEANROOM_DISINFECTING_QUARTERS, "Cleanroom Disinfecting Quarters");
        translationBuilder.add(ModBlocks.CLEANROOM_FLUORESCENT_LAMP, "Cleanroom Fluorescent Lamp");
        translationBuilder.add(ModBlocks.CLEANROOM_LORRY, "Cleanroom Lorry");
        translationBuilder.add(ModBlocks.CLEANROOM_MATERIALS_BOX, "Cleanroom Materials Box");
        translationBuilder.add(ModBlocks.CLEANROOM_PIPE_VALVE, "Cleanroom Pipe Valve");
        translationBuilder.add(ModBlocks.EMERGENCY_STRETCHER, "Emergency Stretcher");
        translationBuilder.add(ModBlocks.MULTIFUNCTIONAL_STERILIZER, "Multifunctional Sterilizer");
        translationBuilder.add(ModBlocks.MULTIFUNCTIONAL_ENGINEERING_SHOVEL, "Multifunctional Engineering Shovel");
        translationBuilder.add(ModBlocks.SUPPLY_TANKS, "Supply Tanks");

        translationBuilder.add(ModBlocks.BANQUET_GUEST_SEAT, "Banquet Guest Seat");
        translationBuilder.add(ModBlocks.BANQUET_HOST_SEAT, "Banquet Host Seat");
        translationBuilder.add(ModBlocks.BANQUET_TABLE, "Banquet Table");
        translationBuilder.add(ModBlocks.CANDLE_CHANDELIER, "Candle Chandelier");
        translationBuilder.add(ModBlocks.CANLELIT_HEARTH, "Candlelit Hearth");
        translationBuilder.add(ModBlocks.DOUBLE_DECKER_CHANDELIER, "Double Decker Chandelier");
        translationBuilder.add(ModBlocks.LOCKED_CABINET, "Locked Cabinet");
        translationBuilder.add(ModBlocks.IONIC_COLUMN_DOWN, "Ionic Column Down");
        translationBuilder.add(ModBlocks.IONIC_COLUMN_UP, "Ionic Column Up");
        translationBuilder.add(ModBlocks.IONIC_COLUMN_MIDDLE, "Ionic Column Middle");
        translationBuilder.add(ModBlocks.REIMSELAR_BRAZIER, "Reimselar Brazier");
        translationBuilder.add(ModBlocks.REIMSELAR_GUARDS_BUST, "Reimselar Guard's Bust");
        translationBuilder.add(ModBlocks.REIMSELAR_MAGIC_MIRROR, "Reimselar Magic Mirror");
        translationBuilder.add(ModBlocks.REIMSELAR_STOOL, "Reimselar Stool");

        translationBuilder.add("itemGroup.logo", "Logo");
        translationBuilder.add("itemGroup.material", "Material");
        translationBuilder.add("itemGroup.warehouse", "Warehouse");
        translationBuilder.add("itemGroup.side_line", "Side Line/ Simple Black-and-white/Orange Furniture");
        translationBuilder.add("itemGroup.fantastic_bio-documentary", "Fantastic Bio-Documentary");
        translationBuilder.add("itemGroup.no_12_life_cycle_cabin", "No.12 Life Cycle Cabin");
        translationBuilder.add("itemGroup.columbian_cafe", "Columbian Cafe");
        translationBuilder.add("itemGroup.ldg_faux_lungmen_lounge", "L.D.G./Faux Lungmen Lounge");
        translationBuilder.add("itemGroup.sami_countryside_villa", "Sami Countryside Villa");
        translationBuilder.add("itemGroup.express_chain_pizzeria", "Express Chain Pizzeria");
        translationBuilder.add("itemGroup.modern_columbian_hotel", "Modern Columbian Hotel");
        translationBuilder.add("itemGroup.chens_office", "Ch'en's Office");
        translationBuilder.add("itemGroup.siesta_beach_hut", "Siesta Beach Hut");
        translationBuilder.add("itemGroup.rhodes_island_modern_music_rehearsal_room", "Rhodes Island Modern Music Rehearsal Room");
        translationBuilder.add("itemGroup.airtight_anti-chemical_safety_cabin", "Airtight Anti-Chemical Safety Cabin");
        translationBuilder.add("itemGroup.reimselar_ballroom", "Reimselar Ballroom");

        translationBuilder.add("container.carton", "Carton");
        translationBuilder.add("container.large_shelf", "Large Shelf");
        translationBuilder.add("container.nightstand", "Nightstand");
        translationBuilder.add("container.simple_cabinet", "Simple Cabinet");
        translationBuilder.add("container.checkerboard_bookcase", "Checkerboard Bookcase");
        translationBuilder.add("container.small_square_nightstand", "Small Square Nightstand");
        translationBuilder.add("container.red_brown_cabinet", "Red Brown Cabinet");
        translationBuilder.add("container.small_sandalwood_nightstand", "Small Nightstand");
        translationBuilder.add("container.log_cabinet_bottom", "Log Cabinet Bottom");
        translationBuilder.add("container.log_cabinet_top", "Log Cabinet Top");
        translationBuilder.add("container.pizzeria_cupboard", "Pizzeria Cupboard");
        translationBuilder.add("container.lgd_bookcase", "L.D.G. Bookcase");
        translationBuilder.add("container.summer_boat_cabinet", "Summer Boat Cabinet");
        translationBuilder.add("container.locked_cabinet", "Locked Cabinet");

    }
}
