package com.besson.arknights.datagen;

import com.besson.arknights.block.ModBlocks;
import com.besson.arknights.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.client.*;

public class ModModelsProvider extends FabricModelProvider {
    public ModModelsProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator generator) {
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.AIR_MATTRESS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ATTENDANCE_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CARGO_TROLLEY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CARTON);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CARTON_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAFFITI);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF3);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF4);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF_EMPTY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PALLET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PILE_OF_CARTONS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PORTABLE_CALCULATOR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.POST_IT_NOTE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_ROW_LIGHT);
        generator.registerParentedItemModel(ModBlocks.CONCRETE_WALL, ModelIds.getBlockModelId(ModBlocks.CONCRETE_WALL));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DORMITORY_DOOR_FRAMES);
        generator.registerParentedItemModel(ModBlocks.REINFORCED_CONCRETE_WALLS, ModelIds.getBlockModelId(ModBlocks.REINFORCED_CONCRETE_WALLS));

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_CLOCK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_HD_TV);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_NIGHTSTAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_CALLBOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_AND_WHITE_SQUARE_TABLE);
        generator.registerParentedItemModel(ModBlocks.LOW_BLACK_AND_WHITE_SOFA, ModelIds.getBlockModelId(ModBlocks.LOW_BLACK_AND_WHITE_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_BBL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_BBR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_BTL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_BTR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_MBL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_MBR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_MTL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_MTR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_TL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE_TR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_OFFICE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_LBL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_LBR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_LTL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_LTR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_RBL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_RBR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_RTL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_RTR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAY_FIBER_CARPET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_BBL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_BBR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_BTL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_BTR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_TBL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_TBR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_TTL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_TTR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_CEILING_LIGHT);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_WALL_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_CLOCK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_HD_TV);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_NIGHTSTAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_NOTICEBOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_SQUARE_TABLE);
        generator.registerParentedItemModel(ModBlocks.LOW_ORANGE_SOFA, ModelIds.getBlockModelId(ModBlocks.LOW_ORANGE_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE3);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_SWIVEL_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_DESK_LEFT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_DESK_RIGHT);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BEAN_BAG_SOFA);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ECO_EXHIBITION_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ECO_EXHIBITION_CABINET_BASE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUSH_MOUNT_RECTANGLE_CEILING_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUSH_MOUNT_SQUARE_CEILING_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.METALLIC_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_BROADLEAF_PLANT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_CONIFER_PLANT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_SUCCULENT_PLANT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_SQUARE_NIGHTSTAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SPECIMEN_DATA_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WIRE_SIDE_TABLE);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ANTI_EXPLOSION_TRASH_CAN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BUILT_IN_FILE_CABINET1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BUILT_IN_FILE_CABINET2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BUNK_BED_IN_CABIN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CABIN_FIRE_EXTINGUISHER_KIT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CABIN_FLUSH_MOUNT_PIPE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CONTROL_DISPLAY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DIY_SWIVEL_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DIY_WORKBENCH_LEFT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DIY_WORKBENCH_RIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GENERAL_CONSOLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.NOTE_BOARD_IN_CABIN);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BAR_CEILING);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BARSTOOL_WITH_CURVED_LEGS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_COFFEE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_EMPTY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_MENU);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BOLIVARIAN_COFFEE_BEAN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BRICK_PATTERN_WALLPAPER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BRICK_PATTERN_WALLPAPER_FLOOR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE_LB);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE_LM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE_LT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE_RB);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE_RM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE_RT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.COFFEE_BEAN_CAN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.COFFEE_BEAN_DISPLAY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.COFFEE_MENU);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.COLUMBIAN_STREET_VIEW_PHOTO);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DINING_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PEDESTAL_COFFEE_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PENDANT_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_LONG_LEAF_PLANT);
        generator.registerParentedItemModel(ModBlocks.RED_BRICK_CAFE_BAR, ModelIds.getBlockModelId(ModBlocks.RED_BRICK_CAFE_BAR));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_BROWN_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SOFT_CEILING_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WOOD_ORNAMENT);
        generator.registerSimpleState(ModBlocks.CAFE_FLOOR);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_PEDESTAL_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_VINTAGE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_VINTAGE_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BRIGHT_WALL_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DUPLEX_WOODEN_FENCE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_SANDALWOOD_MEETING_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SANDALWOOD_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SANDALWOOD_MEETING_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_LOUNGE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_SANDALWOOD_NIGHTSTAND);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DUPLEX_BRONZE_FENCE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_TEAK_MEETING_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIANO_BLACK_VINTAGE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIANO_BLACK_VINTAGE_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_GRAY_LOUNGE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_TEAK_NIGHTSTAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TEAK_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TEAK_ATTENDANCE_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WHITE_PEDESTAL_TABLE);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CREATURES_REMAINS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FUTON_BUNK_BED_BOTTOM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FUTON_BUNK_BED_TOP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HANDMADE_WOOD_BASKET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_BEAM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_CABINET_BOTTOM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_CABINET_TOP1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_CABINET_TOP2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_DINING_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_DINING_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ROCKING_CHAIR_WITH_CUSHION);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SPRUCE_WOOD_VIOLIN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.VINTAGE_CEILING_FAN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.VINTAGE_CEILING_LIGHT);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DINING_PLATE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_BOWL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_BOX);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_MENU1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_MENU2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_BLACK_COUNTER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_CUPBOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_DINING_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_EXIT_SIGN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_HIGH_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_MOVEABLE_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_PLATE_RACK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_POSTER_COLUMN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_POSTER_STAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_SOFT_CEILING_LIGHT);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BARSTOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BILLBOARD_JUKEBOX);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_AND_GOLDEN_FREEZER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_CEILING_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_FLOOR_LAMP);
        generator.registerParentedItemModel(ModBlocks.MODERN_HOTEL_SOFA, ModelIds.getBlockModelId(ModBlocks.MODERN_HOTEL_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_WALL_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_WALL_DECORATION);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MOUNTED_BAR_CEILING1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MOUNTED_BAR_CEILING2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.VERSATILE_BAR_STAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WILLIAMS_GRAND_PIANO_SET);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHENS_CERTIFICATE_OF_HONOR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHENS_CHAIR);
        generator.registerParentedItemModel(ModBlocks.CHENS_DESK, ModelIds.getBlockModelId(ModBlocks.CHENS_DESK));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CHENS_WEAPON_RACK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FILE1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FILE2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_BOOKCASE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_DAYLIGHT_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_FLUORESCENT_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_SPECIAL_DUMMY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_SPOTLIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_SUPINE_PLATE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_TRASH_CAN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.OFFICE_CLUE_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_CACTUS_PLANT);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BEACH_HOUSE_FLOOR_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLUE_AND_WHITE_CANVAS_CURTAINS_LEFT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BLUE_AND_WHITE_CANVAS_CURTAINS_RIGHT);
        generator.registerParentedItemModel(ModBlocks.LAZY_BENCH, ModelIds.getBlockModelId(ModBlocks.LAZY_BENCH));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LAZY_COFFEE_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LAZY_HIGH_TEA_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LAZY_LOUNGE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RHODES_ISLAND_SUMMER_CALENDAR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIESTA_COAT_OF_ARMS_SOUVENIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_BOAT_CABINET_BOTTOM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_BOAT_CABINET_TOP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_COLLECTION_SHELF);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_COLLECTION_SHELF_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SURFBOARD_STAND);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WOODEN_BEAM);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.AMBER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BIRCH);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DARK_CLOUD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DARK_STEEL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DRIFTWOOD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FLAME);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRIT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_SCROLLING_DISPLAY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_ACCESSORY_SHELF);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_BELT_SHELF);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_BENCH);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_RECEPTION_DESK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_ROUND_BENCH);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_SPOTLIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SHALLOW_SEA);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SPOTLIGHT_CEILING);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STAGE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TOUR_INSTRUMENT_COMBO);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WHEAT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.YARMAHAN_DRUM_SET);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_AIRDUCT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_AIRFLOW_CONTROL_PIPE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_ANTIMICROBIAL_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_CEILING_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_DISINFECTING_QUARTERS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_FLUORESCENT_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_LORRY);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_MATERIALS_BOX);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_PIPE_VALVE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.EMERGENCY_STRETCHER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_ENGINEERING_SHOVEL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_STERILIZER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SUPPLY_TANKS);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BANQUET_GUEST_SEAT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BANQUET_HOST_SEAT);
        generator.registerParentedItemModel(ModBlocks.BANQUET_TABLE, ModelIds.getBlockModelId(ModBlocks.BANQUET_TABLE));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CANDLE_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CANLELIT_HEARTH);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DOUBLE_DECKER_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOCKED_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.IONIC_COLUMN_DOWN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.IONIC_COLUMN_MIDDLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.IONIC_COLUMN_UP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_BRAZIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_GUARDS_BUST);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_MAGIC_MIRROR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_STOOL);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BOARDED_UP_STONE_WINDOWS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CAULDRON_OF_SWEETS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DESK_OF_THE_OCCULT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ELEGANT_SEAT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MANY_RITUAL_GOURDS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RITUAL_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SEVERAL_RITUAL_GOURDS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STACK_OF_GRIMOIRES);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STRANGE_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STRANGE_BED_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STRANGE_BED_TREE);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ADJUSTABLE_ROUND_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.COLLECTIBLE_BEVERAGE_DISPENSER);
        generator.registerParentedItemModel(ModBlocks.COMFORTABLE_SOFA, ModelIds.getBlockModelId(ModBlocks.COMFORTABLE_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUORESCENT_CEILING_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HIGH_POWER_FLOOR_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_WORKBENCH);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_WORKBENCH_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_WORKBENCH_COMPUTER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.OLD_RECORD_PLAYER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.OUTGOING_SHIPMENTS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PENGUIN_CLUE_COLLECTION_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_SUNDRIES_SHELVES1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_SUNDRIES_SHELVES2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_SUNDRIES_SHELVES3);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SAFEHOUSE_PARTITION_DOOR);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_FLOODLIGHTS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANSER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DUAL_BEAMED_CRANE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INDUSTRIAL_CUTTING_STATION);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MATERIAL_CRATES);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ROBOTIC_ARM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WEAPON_STORAGE_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WHITE_ROUND_STOOL);
        generator.registerParentedItemModel(ModBlocks.WORKBENCH, ModelIds.getBlockModelId(ModBlocks.WORKBENCH));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WORKSTATION_BLACKBOARD);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BAMBOO_SCREEN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BOILING_STATION);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BOILING_STATION_POT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_MOUNTED_LIGHTS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.EATERY_DINING_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.EATERY_ROUND_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ELECTRIC_FRYING_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HALF_SHUT_SCREEN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEXAGONAL_LANTERN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_FANG);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_JIAO);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_LEFT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_LONG);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_MENG);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_MENU1);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_MENU2);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_RIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_ZI);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORNAMENTAL_BONSAI);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ORNAMENTAL_PLANT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RECTANGULAR_BENCH);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_SPOTLIGHT);
        generator.registerParentedItemModel(ModBlocks.WOODEN_CORNER_TABLE, ModelIds.getBlockModelId(ModBlocks.WOODEN_CORNER_TABLE));

        generator.registerParentedItemModel(ModBlocks.FRESH_FOOD_CABINET, ModelIds.getBlockModelId(ModBlocks.FRESH_FOOD_CABINET));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GARDEN_STYLE_CEILING_FIXTURE);
        generator.registerParentedItemModel(ModBlocks.GREEN_TWO_SEAT_SOFA, ModelIds.getBlockModelId(ModBlocks.GREEN_TWO_SEAT_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_DECORATIVE_PLATE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_DINING_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_MENU);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_SERVICE_COUNTER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_SERVICE_COUNTER_CASHIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_SPOTLIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ICEY_JUICER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SELF_SERVICE_ORDERING_KIOSK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TODAYS_RECOMMENDATIONS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.VENDING_MACHINE);

        generator.registerParentedItemModel(ModBlocks.DOUBLE_ROW_SEATING, ModelIds.getBlockModelId(ModBlocks.DOUBLE_ROW_SEATING));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.DOUBLE_ROW_SEATING_DESK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GOURMET_FOOD_WARMER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_NOTICE_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LIQUOR_STORAGE_RACK);
        generator.registerParentedItemModel(ModBlocks.PRISTINE_SERVICE_COUNTER, ModelIds.getBlockModelId(ModBlocks.PRISTINE_SERVICE_COUNTER));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RESTAURANT_NOTICE_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SEVEN_CITIES_WARM_LIGHT_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.UPSCALE_MENU_DISPLAY);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BOUNTY_DISPLAY_RACK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.BULLETPROOF_GLASS_DOOR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_DARTBOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_SHELVES);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HIGH_OUTPUT_EXPLOSIVE_MATERIAL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.IGNITION_TOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_BULLETIN_BOARD);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_CEILING_LIGHT_FIXTURE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_TUBE_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_FRAMED_FLOOR_MIRROR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SARKAZ_BALL_RACK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SARKAZ_POOL_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_LOUNGE_WALL_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.UPSCALE_DINING_TABLE);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_DISK_LIGHT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LONG_WOODEN_TABLE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_BOOKSHELF);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_FLOOR_LAMP);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_STORAGE_CABINET);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PORTABLE_PICNIC_STOVE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_LOW_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SQUAD_BULLETIN_BOARD);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ACCOMPANISTS_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ALL_IN_ONE_BOOKSHELF);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ALL_IN_ONE_BOOKSHELF_BOTTOM);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ALL_IN_ONE_BOOKSHELF_UPPER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.ANTIQUE_PHONOGRAPH);
        generator.registerParentedItemModel(ModBlocks.EXTRA_LONG_WHITE_SOFA, ModelIds.getBlockModelId(ModBlocks.EXTRA_LONG_WHITE_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FOUR_CANDLE_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FOUR_POSTER_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GLOBE_OF_BALANCE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAND_SIX_CANDLE_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.LEITHANIAN_BEVERAGE);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.MONOCHROMATIC_CELLO);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PILE_OF_MISCELLANEOUS_BOOKS);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CUBICLE_FLOORPLAN);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.CUBICLE_LIGHTING);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.FLOOR_INDICATOR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.HR_OFFICE_LIGHTING);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.OVERLOADED_PRINTER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.PRICKLY_ORNAMENTAL_PLANT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.SQUARE_SOFA_STOOL);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STANDARD_ISSUE_OFFICE_CHAIR);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STANDARD_ISSUE_WORKDESK);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.STANDARD_ISSUE_WORKDESK_COMPUTER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TRANSPARENT_DIVIDING_PARTITION);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WATER_DISPENSER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.WHEELED_STORAGE_CABINET);

        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TOTEM_POT);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TOTEM_SPEAKERS);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TRIBAL_DECORATIVE_CHANDELIER);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TRIBAL_LOFT_BED);
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TRIBAL_STONE_STAND);
        generator.registerParentedItemModel(ModBlocks.TRIBAL_STYLE_SOFA, ModelIds.getBlockModelId(ModBlocks.TRIBAL_STYLE_SOFA));
        generator.registerNorthDefaultHorizontalRotation(ModBlocks.TROPICAL_POTTED_PLANT);

    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.ABYSSAL_HUNTERS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.AEGIR_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BABEL_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_STEEL_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BOLIVAR_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.COLUMBIA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.DONG_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.DUBLINN_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.ELITE_OP_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.FOLLOWERS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.GLASGOW_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.IBERIA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.KARLAN_TRADE_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.KAZIMIERZ_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.KJERAG_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LATERANO_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LEES_DETECTIVE_AGENCY_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LEITHANIEN_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LUNGMEN_GUARD_DEPARTMENT_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LUNGMEN_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.MINOS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_A4_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_RESERVE_A1_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_RESERVE_A4_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_RESERVE_A6_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.PENGUIN_LOGISTICS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINUS_SYLVESTRIS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHINE_LAB_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHODES_ISLAND_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHODES_ISLAND_OVERRIDE_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RIM_BILLITON_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAMI_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SARGON_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIESTA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIRACUSA_BRANCHES_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIRACUSA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SUI_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SWEEP_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.TEAM_RAINBOW_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.URSUS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.URSUS_STUDENT_SELF_GOVERNING_GROUP_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.VICTORIA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAN_LOGO, Models.GENERATED);

        itemModelGenerator.register(ModItems.FURN_PARTS, Models.GENERATED);
        itemModelGenerator.register(ModItems.CARDBOARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.FURN_PARTS_ZIP1, Models.GENERATED);
        itemModelGenerator.register(ModItems.FURN_PARTS_ZIP2, Models.GENERATED);

        itemModelGenerator.register(ModItems.TAPE, Models.GENERATED);
    }
}
