package com.besson.arknights.datagen;

import com.besson.arknights.block.ModBlocks;
import com.besson.arknights.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.client.*;

public class ModModelsProvider extends FabricModelProvider {
    public ModModelsProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.AIR_MATTRESS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ATTENDANCE_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CARGO_TROLLEY);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CARTON);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CARTON_STOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAFFITI);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF3);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_SHELF4);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PALLET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PILE_OF_CARTONS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PORTABLE_CALCULATOR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.POST_IT_NOTE);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAYISH_WALL_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_CLOCK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_HD_TV);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_NIGHTSTAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_CALLBOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_AND_WHITE_SQUARE_TABLE);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LOW_BLACK_AND_WHITE_SOFA, ModelIds.getBlockModelId(ModBlocks.LOW_BLACK_AND_WHITE_SOFA));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CHECKERBOARD_BOOKCASE3);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_OFFICE_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_LEFT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_DESK_RIGHT);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_WALL_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_CLOCK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_HD_TV);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_NIGHTSTAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_NOTICEBOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_SQUARE_TABLE);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LOW_ORANGE_SOFA, ModelIds.getBlockModelId(ModBlocks.LOW_ORANGE_SOFA));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE3);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORANGE_SWIVEL_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_DESK_LEFT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_ORANGE_DESK_RIGHT);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BEAN_BAG_SOFA);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ECO_EXHIBITION_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ECO_EXHIBITION_CABINET_BASE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUSH_MOUNT_RECTANGLE_CEILING_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUSH_MOUNT_SQUARE_CEILING_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.METALLIC_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_BROADLEAF_PLANT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_CONIFER_PLANT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_SUCCULENT_PLANT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_SQUARE_NIGHTSTAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SPECIMEN_DATA_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WIRE_SIDE_TABLE);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ANTI_EXPLOSION_TRASH_CAN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BUILT_IN_FILE_CABINET1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BUILT_IN_FILE_CABINET2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BUNK_BED_IN_CABIN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CABIN_FIRE_EXTINGUISHER_KIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CABIN_FLUSH_MOUNT_PIPE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CONTROL_DISPLAY);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DIY_SWIVEL_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DIY_WORKBENCH_LEFT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DIY_WORKBENCH_RIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GENERAL_CONSOLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.NOTE_BOARD_IN_CABIN);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BAR_CEILING);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BARSTOOL_WITH_CURVED_LEGS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_COFFEE1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_COFFEE2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_DC);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_DRINK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_CABINET_EMPTY);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEVERAGE_MENU);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BOLIVARIAN_COFFEE_BEAN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BROWN_BOOKCASE3);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.COLUMBIAN_STREET_VIEW_PHOTO);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DINING_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PEDESTAL_COFFEE_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PENDANT_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_LONG_LEAF_PLANT);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RED_BRICK_CAFE_BAR, ModelIds.getBlockModelId(ModBlocks.RED_BRICK_CAFE_BAR));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_BROWN_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SOFT_CEILING_LIGHT);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_PEDESTAL_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_VINTAGE_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_VINTAGE_STOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BRIGHT_WALL_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DUPLEX_WOODEN_FENCE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_SANDALWOOD_MEETING_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SANDALWOOD_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SANDALWOOD_MEETING_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_BLACK_LOUNGE_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_SANDALWOOD_NIGHTSTAND);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DUPLEX_BRONZE_FENCE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_TEAK_MEETING_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIANO_BLACK_VINTAGE_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIANO_BLACK_VINTAGE_STOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_GRAY_LOUNGE_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_TEAK_NIGHTSTAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.TEAK_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.TEAK_ATTENDANCE_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WHITE_PEDESTAL_TABLE);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CREATURES_REMAINS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FUTON_BUNK_BED_BOTTOM);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FUTON_BUNK_BED_TOP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HANDMADE_WOOD_BASKET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_BEAM);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_CABINET_BOTTOM);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_CABINET_TOP1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_CABINET_TOP2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_DINING_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOG_DINING_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ROCKING_CHAIR_WITH_CUSHION);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SPRUCE_WOOD_VIOLIN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.VINTAGE_CEILING_FAN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.VINTAGE_CEILING_LIGHT);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DINING_PLATE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_BOWL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_BOX);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_MENU1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZA_MENU2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_BLACK_COUNTER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_CUPBOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_DINING_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_EXIT_SIGN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_HIGH_STOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_MOVEABLE_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_PLATE_RACK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_POSTER_COLUMN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_POSTER_STAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PIZZERIA_SOFT_CEILING_LIGHT);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BARSTOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BILLBOARD_JUKEBOX);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLACK_AND_GOLDEN_FREEZER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_CEILING_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_FLOOR_LAMP);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MODERN_HOTEL_SOFA, ModelIds.getBlockModelId(ModBlocks.MODERN_HOTEL_SOFA));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_HOTEL_WALL_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MODERN_WALL_DECORATION);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MOUNTED_BAR_CEILING1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MOUNTED_BAR_CEILING2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.VERSATILE_BAR_STAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WILLIAMS_GRAND_PIANO_SET);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CHENS_CERTIFICATE_OF_HONOR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CHENS_CHAIR);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.CHENS_DESK, ModelIds.getBlockModelId(ModBlocks.CHENS_DESK));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CHENS_WEAPON_RACK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FILE1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FILE2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_BOOKCASE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_DAYLIGHT_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_FLUORESCENT_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_SPECIAL_DUMMY);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_SPOTLIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_SUPINE_PLATE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LGD_TRASH_CAN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.OFFICE_CLUE_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.POTTED_CACTUS_PLANT);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BEACH_HOUSE_FLOOR_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLUE_AND_WHITE_CANVAS_CURTAINS_LEFT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BLUE_AND_WHITE_CANVAS_CURTAINS_RIGHT);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LAZY_BENCH, ModelIds.getBlockModelId(ModBlocks.LAZY_BENCH));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LAZY_COFFEE_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LAZY_HIGH_TEA_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LAZY_LOUNGE_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RHODES_ISLAND_SUMMER_CALENDAR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIESTA_COAT_OF_ARMS_SOUVENIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_BOAT_CABINET_BOTTOM);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_BOAT_CABINET_TOP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_COLLECTION_SHELF);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SUMMER_COLLECTION_SHELF_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SURFBOARD_STAND);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WOODEN_BEAM);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.AMBER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BIRCH);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DARK_CLOUD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DARK_STEEL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DRIFTWOOD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FLAME);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GRIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_SCROLLING_DISPLAY);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_ACCESSORY_SHELF);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_BELT_SHELF);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_BENCH);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_RECEPTION_DESK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_ROUND_BENCH);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REHEARSAL_ROOM_SPOTLIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SHALLOW_SEA);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SPOTLIGHT_CEILING);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.STAGE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.TOUR_INSTRUMENT_COMBO);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WHEAT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.YARMAHAN_DRUM_SET);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_AIRDUCT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_AIRFLOW_CONTROL_PIPE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_ANTIMICROBIAL_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_CEILING_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_DISINFECTING_QUARTERS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_FLUORESCENT_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_LORRY);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_MATERIALS_BOX);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANROOM_PIPE_VALVE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.EMERGENCY_STRETCHER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_ENGINEERING_SHOVEL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_STERILIZER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SUPPLY_TANKS);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BANQUET_GUEST_SEAT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BANQUET_HOST_SEAT);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BANQUET_TABLE, ModelIds.getBlockModelId(ModBlocks.BANQUET_TABLE));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CANDLE_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CANLELIT_HEARTH);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DOUBLE_DECKER_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOCKED_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.IONIC_COLUMN_DOWN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.IONIC_COLUMN_MIDDLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.IONIC_COLUMN_UP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_BRAZIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_GUARDS_BUST);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_MAGIC_MIRROR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REIMSELAR_STOOL);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BOARDED_UP_STONE_WINDOWS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CAULDRON_OF_SWEETS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DESK_OF_THE_OCCULT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ELEGANT_SEAT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MANY_RITUAL_GOURDS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RITUAL_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SEVERAL_RITUAL_GOURDS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.STACK_OF_GRIMOIRES);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.STRANGE_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.STRANGE_BED_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.STRANGE_BED_TREE);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ADJUSTABLE_ROUND_STOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.COLLECTIBLE_BEVERAGE_DISPENSER);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMFORTABLE_SOFA, ModelIds.getBlockModelId(ModBlocks.COMFORTABLE_SOFA));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUORESCENT_CEILING_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HIGH_POWER_FLOOR_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_WORKBENCH);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_WORKBENCH_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MULTIFUNCTIONAL_WORKBENCH_COMPUTER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.OLD_RECORD_PLAYER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.OUTGOING_SHIPMENTS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PENGUIN_CLUE_COLLECTION_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_SUNDRIES_SHELVES1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_SUNDRIES_SHELVES2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_SUNDRIES_SHELVES3);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SAFEHOUSE_PARTITION_DOOR);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_FLOODLIGHTS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CLEANSER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DUAL_BEAMED_CRANE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INDUSTRIAL_CUTTING_STATION);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MATERIAL_CRATES);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ROBOTIC_ARM);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WEAPON_STORAGE_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WHITE_ROUND_STOOL);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.WORKBENCH, ModelIds.getBlockModelId(ModBlocks.WORKBENCH));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.WORKSTATION_BLACKBOARD);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BAMBOO_SCREEN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BOILING_STATION);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BOILING_STATION_POT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_MOUNTED_LIGHTS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.EATERY_DINING_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.EATERY_ROUND_STOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ELECTRIC_FRYING_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HALF_SHUT_SCREEN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEXAGONAL_LANTERN);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_FANG);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_JIAO);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_LEFT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_LONG);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_MENG);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_MENU1);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_MENU2);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_RIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.INSCRIPTION_CEILING_PLAQUE_ZI);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORNAMENTAL_BONSAI);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ORNAMENTAL_PLANT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RECTANGULAR_BENCH);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_SPOTLIGHT);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.WOODEN_CORNER_TABLE, ModelIds.getBlockModelId(ModBlocks.WOODEN_CORNER_TABLE));

        blockStateModelGenerator.registerParentedItemModel(ModBlocks.FRESH_FOOD_CABINET, ModelIds.getBlockModelId(ModBlocks.FRESH_FOOD_CABINET));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GARDEN_STYLE_CEILING_FIXTURE);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GREEN_TWO_SEAT_SOFA, ModelIds.getBlockModelId(ModBlocks.GREEN_TWO_SEAT_SOFA));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_DECORATIVE_PLATE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_DINING_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_MENU);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_SERVICE_COUNTER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_SERVICE_COUNTER_CASHIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HEALTHY_SPOTLIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ICEY_JUICER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SELF_SERVICE_ORDERING_KIOSK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.TODAYS_RECOMMENDATIONS);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.VENDING_MACHINE);

        blockStateModelGenerator.registerParentedItemModel(ModBlocks.DOUBLE_ROW_SEATING, ModelIds.getBlockModelId(ModBlocks.DOUBLE_ROW_SEATING));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.DOUBLE_ROW_SEATING_DESK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GOURMET_FOOD_WARMER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LARGE_NOTICE_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LIQUOR_STORAGE_RACK);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PRISTINE_SERVICE_COUNTER, ModelIds.getBlockModelId(ModBlocks.PRISTINE_SERVICE_COUNTER));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RESTAURANT_NOTICE_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SEVEN_CITIES_WARM_LIGHT_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.UPSCALE_MENU_DISPLAY);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BOUNTY_DISPLAY_RACK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.BULLETPROOF_GLASS_DOOR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_DARTBOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_SHELVES);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HIGH_OUTPUT_EXPLOSIVE_MATERIAL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.IGNITION_TOOL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_BULLETIN_BOARD);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_CEILING_LIGHT_FIXTURE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOUNGE_TUBE_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RED_FRAMED_FLOOR_MIRROR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SARKAZ_BALL_RACK);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SARKAZ_POOL_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SMALL_LOUNGE_WALL_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.UPSCALE_DINING_TABLE);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.CEILING_DISK_LIGHT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.HANGING_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LONG_WOODEN_TABLE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_BOOKSHELF);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_FLOOR_LAMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LOW_STORAGE_CABINET);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PORTABLE_PICNIC_STOVE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SIMPLE_LOW_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SQUAD_BULLETIN_BOARD);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ACCOMPANISTS_CHAIR);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ALL_IN_ONE_BOOKSHELF);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ALL_IN_ONE_BOOKSHELF_BOTTOM);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ALL_IN_ONE_BOOKSHELF_UPPER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ANTIQUE_PHONOGRAPH);
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.EXTRA_LONG_WHITE_SOFA, ModelIds.getBlockModelId(ModBlocks.EXTRA_LONG_WHITE_SOFA));
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FOUR_CANDLE_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FOUR_POSTER_BED);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GLOBE_OF_BALANCE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GRAND_SIX_CANDLE_CHANDELIER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.LEITHANIAN_BEVERAGE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MONOCHROMATIC_CELLO);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PILE_OF_MISCELLANEOUS_BOOKS);

    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.ABYSSAL_HUNTERS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.AEGIR_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BABEL_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_STEEL_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BOLIVAR_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.COLUMBIA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.DONG_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.DUBLINN_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.ELITE_OP_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.FOLLOWERS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.GLASGOW_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.IBERIA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.KARLAN_TRADE_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.KAZIMIERZ_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.KJERAG_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LATERANO_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LEES_DETECTIVE_AGENCY_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LEITHANIEN_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LUNGMEN_GUARD_DEPARTMENT_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.LUNGMEN_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.MINOS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_A4_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_RESERVE_A1_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_RESERVE_A4_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.OP_RESERVE_A6_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.PENGUIN_LOGISTICS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINUS_SYLVESTRIS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHINE_LAB_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHODES_ISLAND_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHODES_ISLAND_OVERRIDE_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.RIM_BILLITON_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAMI_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SARGON_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIESTA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIRACUSA_BRANCHES_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIRACUSA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SUI_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SWEEP_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.TEAM_RAINBOW_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.URSUS_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.URSUS_STUDENT_SELF_GOVERNING_GROUP_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.VICTORIA_LOGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAN_LOGO, Models.GENERATED);

        itemModelGenerator.register(ModItems.FURN_PARTS, Models.GENERATED);
        itemModelGenerator.register(ModItems.CARDBOARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.FURN_PARTS_ZIP1, Models.GENERATED);
        itemModelGenerator.register(ModItems.FURN_PARTS_ZIP2, Models.GENERATED);
    }
}
