package com.besson.arknights.datagen;

import com.besson.arknights.block.ModBlocks;
import com.besson.arknights.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class ModZhCnLangProvider extends FabricLanguageProvider {
    public static final String painting = "painting.arknights-furniture.";
    public ModZhCnLangProvider(FabricDataOutput dataOutput) {
        super(dataOutput, "zh_cn");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModItems.ABYSSAL_HUNTERS_LOGO, "深海猎人 Logo");
        translationBuilder.add(ModItems.AEGIR_LOGO, "阿戈尔 Logo");
        translationBuilder.add(ModItems.BABEL_LOGO, "巴别塔 Logo");
        translationBuilder.add(ModItems.BLACK_STEEL_LOGO, "黑钢国际 Logo");
        translationBuilder.add(ModItems.BOLIVAR_LOGO, "玻利瓦尔 Logo");
        translationBuilder.add(ModItems.COLUMBIA_LOGO, "哥伦比亚 Logo");
        translationBuilder.add(ModItems.DONG_LOGO, "东 Logo");
        translationBuilder.add(ModItems.DUBLINN_LOGO, "深池 Logo");
        translationBuilder.add(ModItems.ELITE_OP_LOGO, "罗德岛精英干员 Logo");
        translationBuilder.add(ModItems.FOLLOWERS_LOGO, "使徒 Logo");
        translationBuilder.add(ModItems.GLASGOW_LOGO, "格拉斯帮 Logo");
        translationBuilder.add(ModItems.IBERIA_LOGO, "伊比利亚 Logo");
        translationBuilder.add(ModItems.KARLAN_TRADE_LOGO, "喀兰贸易 Logo");
        translationBuilder.add(ModItems.KAZIMIERZ_LOGO, "卡西米尔 Logo");
        translationBuilder.add(ModItems.KJERAG_LOGO, "谢拉格 Logo");
        translationBuilder.add(ModItems.LATERANO_LOGO, "拉特兰 Logo");
        translationBuilder.add(ModItems.LEES_DETECTIVE_AGENCY_LOGO, "鲤氏侦探事务所 Logo");
        translationBuilder.add(ModItems.LEITHANIEN_LOGO, "莱塔尼亚 Logo");
        translationBuilder.add(ModItems.LUNGMEN_GUARD_DEPARTMENT_LOGO, "龙门近卫局 Logo");
        translationBuilder.add(ModItems.LUNGMEN_LOGO, "龙门 Logo");
        translationBuilder.add(ModItems.MINOS_LOGO, "米诺斯 Logo");
        translationBuilder.add(ModItems.OP_A4_LOGO, "行动组A4 Logo");
        translationBuilder.add(ModItems.OP_RESERVE_A1_LOGO, "行动预备组A1 Logo");
        translationBuilder.add(ModItems.OP_RESERVE_A4_LOGO, "行动预备组A4 Logo");
        translationBuilder.add(ModItems.OP_RESERVE_A6_LOGO, "行动预备组A6 Logo");
        translationBuilder.add(ModItems.PENGUIN_LOGISTICS_LOGO, "企鹅物流 Logo");
        translationBuilder.add(ModItems.PINUS_SYLVESTRIS_LOGO, "红松骑士团 Logo");
        translationBuilder.add(ModItems.RHINE_LAB_LOGO, "莱茵生命 Logo");
        translationBuilder.add(ModItems.RHODES_ISLAND_LOGO, "罗德岛 Logo");
        translationBuilder.add(ModItems.RHODES_ISLAND_OVERRIDE_LOGO, "罗德岛（重制） Logo");
        translationBuilder.add(ModItems.RIM_BILLITON_LOGO, "雷姆必拓 Logo");
        translationBuilder.add(ModItems.SAMI_LOGO, "萨米 Logo");
        translationBuilder.add(ModItems.SARGON_LOGO, "萨尔贡 Logo");
        translationBuilder.add(ModItems.SIESTA_LOGO, "汐斯塔 Logo");
        translationBuilder.add(ModItems.SIRACUSA_BRANCHES_LOGO, "贾维团伙 Logo");
        translationBuilder.add(ModItems.SIRACUSA_LOGO, "叙拉古 Logo");
        translationBuilder.add(ModItems.SUI_LOGO, "炎-岁 Logo");
        translationBuilder.add(ModItems.SWEEP_LOGO, "S.W.E.E.P Logo");
        translationBuilder.add(ModItems.TEAM_RAINBOW_LOGO, "彩虹小队 Logo");
        translationBuilder.add(ModItems.URSUS_LOGO, "乌萨斯 Logo");
        translationBuilder.add(ModItems.URSUS_STUDENT_SELF_GOVERNING_GROUP_LOGO, "乌萨斯学生自治团 Logo");
        translationBuilder.add(ModItems.VICTORIA_LOGO, "维多利亚 Logo");
        translationBuilder.add(ModItems.YAN_LOGO, "炎 Logo");

        translationBuilder.add(painting + "abyssal_hunters.title", "深海猎人");
        translationBuilder.add(painting + "abyssal_hunters.author", "鹰角网络");
        translationBuilder.add(painting + "aegir.title", "阿戈尔");
        translationBuilder.add(painting + "aegir.author", "鹰角网络");
        translationBuilder.add(painting + "babel.title", "巴别塔");
        translationBuilder.add(painting + "babel.author", "鹰角网络");
        translationBuilder.add(painting + "black_steel.title", "黑钢国际");
        translationBuilder.add(painting + "black_steel.author", "鹰角网络");
        translationBuilder.add(painting + "bolivar.title", "玻利瓦尔");
        translationBuilder.add(painting + "bolivar.author", "鹰角网络");
        translationBuilder.add(painting + "columbia.title", "哥伦比亚");
        translationBuilder.add(painting + "columbia.author", "鹰角网络");
        translationBuilder.add(painting + "dong.title", "东");
        translationBuilder.add(painting + "dong.author", "鹰角网络");
        translationBuilder.add(painting + "dublinn.title", "深池");
        translationBuilder.add(painting + "dublinn.author", "鹰角网络");
        translationBuilder.add(painting + "elite_op.title", "罗德岛精英干员");
        translationBuilder.add(painting + "elite_op.author", "鹰角网络");
        translationBuilder.add(painting + "followers.title", "使徒");
        translationBuilder.add(painting + "followers.author", "鹰角网络");
        translationBuilder.add(painting + "glasgow.title", "格拉斯帮");
        translationBuilder.add(painting + "glasgow.author", "鹰角网络");
        translationBuilder.add(painting + "iberia.title", "伊比利亚");
        translationBuilder.add(painting + "iberia.author", "鹰角网络");
        translationBuilder.add(painting + "karlan_trade.title", "喀兰贸易");
        translationBuilder.add(painting + "karlan_trade.author", "鹰角网络");
        translationBuilder.add(painting + "kazimierz.title", "卡西米尔");
        translationBuilder.add(painting + "kazimierz.author", "鹰角网络");
        translationBuilder.add(painting + "kjerag.title", "谢拉格");
        translationBuilder.add(painting + "kjerag.author", "鹰角网络");
        translationBuilder.add(painting + "laterano.title", "拉特兰");
        translationBuilder.add(painting + "laterano.author", "鹰角网络");
        translationBuilder.add(painting + "lee-s_detective_agency.title", "鲤氏侦探事务所");
        translationBuilder.add(painting + "lee-s_detective_agency.author", "鹰角网络");
        translationBuilder.add(painting + "leithanien.title", "莱塔尼亚");
        translationBuilder.add(painting + "leithanien.author", "鹰角网络");
        translationBuilder.add(painting + "lungmen_guard_department.title", "龙门近卫局");
        translationBuilder.add(painting + "lungmen_guard_department.author", "鹰角网络");
        translationBuilder.add(painting + "lungmen.title", "龙门");
        translationBuilder.add(painting + "lungmen.author", "鹰角网络");
        translationBuilder.add(painting + "minos.title", "米诺斯");
        translationBuilder.add(painting + "minos.author", "鹰角网络");
        translationBuilder.add(painting + "op_a4.title", "行动组A4");
        translationBuilder.add(painting + "op_a4.author", "鹰角网络");
        translationBuilder.add(painting + "op_reserve_a1.title", "行动预备组A1");
        translationBuilder.add(painting + "op_reserve_a1.author", "鹰角网络");
        translationBuilder.add(painting + "op_reserve_a4.title", "行动预备组A4");
        translationBuilder.add(painting + "op_reserve_a4.author", "鹰角网络");
        translationBuilder.add(painting + "op_reserve_a6.title", "行动预备组A6");
        translationBuilder.add(painting + "op_reserve_a6.author", "鹰角网络");
        translationBuilder.add(painting + "penguin_logistics.title", "企鹅物流");
        translationBuilder.add(painting + "penguin_logistics.author", "鹰角网络");
        translationBuilder.add(painting + "pinus_sylvestris.title", "红松骑士团");
        translationBuilder.add(painting + "pinus_sylvestris.author", "鹰角网络");
        translationBuilder.add(painting + "rhine_lab.title", "莱茵生命");
        translationBuilder.add(painting + "rhine_lab.author", "鹰角网络");
        translationBuilder.add(painting + "rhodes_island.title", "罗德岛");
        translationBuilder.add(painting + "rhodes_island.author", "鹰角网络");
        translationBuilder.add(painting + "rhodes_island_override.title", "罗德岛（重制）");
        translationBuilder.add(painting + "rhodes_island_override.author", "鹰角网络");
        translationBuilder.add(painting + "rim_billiton.title", "雷姆必拓");
        translationBuilder.add(painting + "rim_billiton.author", "鹰角网络");
        translationBuilder.add(painting + "sami.title", "萨米");
        translationBuilder.add(painting + "sami.author", "鹰角网络");
        translationBuilder.add(painting + "sargon.title", "萨尔贡");
        translationBuilder.add(painting + "sargon.author", "鹰角网络");
        translationBuilder.add(painting + "siesta.title", "汐斯塔");
        translationBuilder.add(painting + "siesta.author", "鹰角网络");
        translationBuilder.add(painting + "siracusa_branches.title", "贾维团伙");
        translationBuilder.add(painting + "siracusa_branches.author", "鹰角网络");
        translationBuilder.add(painting + "siracusa.title", "叙拉古");
        translationBuilder.add(painting + "siracusa.author", "鹰角网络");
        translationBuilder.add(painting + "sui.title", "炎-岁");
        translationBuilder.add(painting + "sui.author", "鹰角网络");
        translationBuilder.add(painting + "sweep.title", "S.W.E.E.P");
        translationBuilder.add(painting + "sweep.author", "鹰角网络");
        translationBuilder.add(painting + "team_rainbow.title", "彩虹小队");
        translationBuilder.add(painting + "team_rainbow.author", "鹰角网络");
        translationBuilder.add(painting + "ursus.title", "乌萨斯");
        translationBuilder.add(painting + "ursus.author", "鹰角网络");
        translationBuilder.add(painting + "ursus_student_self-governing_group.title", "乌萨斯学生自治团");
        translationBuilder.add(painting + "ursus_student_self-governing_group.author", "鹰角网络");
        translationBuilder.add(painting + "victoria.title", "维多利亚");
        translationBuilder.add(painting + "victoria.author", "鹰角网络");
        translationBuilder.add(painting + "yan.title", "炎");
        translationBuilder.add(painting + "yan.author", "鹰角网络");
        translationBuilder.add(painting + "unknown_bones.title", "未确认生物骨骼");
        translationBuilder.add(painting + "unknown_bones.author", "鹰角网络");
        translationBuilder.add(painting + "unknown_specimen1.title", "未知生物标本集1");
        translationBuilder.add(painting + "unknown_specimen1.author", "鹰角网络");
        translationBuilder.add(painting + "unknown_specimen2.title", "未知生物标本集2");
        translationBuilder.add(painting + "unknown_specimen2.author", "鹰角网络");
        translationBuilder.add(painting + "unknown_specimen3.title", "未知生物标本集3");
        translationBuilder.add(painting + "unknown_specimen3.author", "鹰角网络");
        translationBuilder.add(painting + "painting_with_sandalwood_frame.title", "檀木相框挂画");
        translationBuilder.add(painting + "painting_with_sandalwood_frame.author", "鹰角网络");
        translationBuilder.add(painting + "painting_with_teak_frame.title", "柚木相框挂画");
        translationBuilder.add(painting + "painting_with_teak_frame.author", "鹰角网络");
        translationBuilder.add(painting + "pizzeria_decorative_painting.title", "披萨店用装饰画");
        translationBuilder.add(painting + "pizzeria_decorative_painting.author", "鹰角网络");

        translationBuilder.add(ModItems.FURN_PARTS, "家具零件");
        translationBuilder.add(ModItems.CARDBOARD, "纸板");
        translationBuilder.add(ModItems.FURN_PARTS_ZIP1, "家具零件 Zip1");
        translationBuilder.add(ModItems.FURN_PARTS_ZIP2, "家具零件 Zip2");

        translationBuilder.add(ModBlocks.AIR_MATTRESS, "实用气垫");
        translationBuilder.add(ModBlocks.ATTENDANCE_BOARD, "轮班考勤板");
        translationBuilder.add(ModBlocks.CARGO_TROLLEY, "货运手推车");
        translationBuilder.add(ModBlocks.CARTON, "纸箱");
        translationBuilder.add(ModBlocks.CARTON_STOOL, "纸箱凳");
        translationBuilder.add(ModBlocks.GRAFFITI, "涂鸦");
        translationBuilder.add(ModBlocks.LARGE_SHELF1, "大号货架1");
        translationBuilder.add(ModBlocks.LARGE_SHELF2, "大号货架2");
        translationBuilder.add(ModBlocks.LARGE_SHELF3, "大号货架3");
        translationBuilder.add(ModBlocks.LARGE_SHELF4, "大号货架4");
        translationBuilder.add(ModBlocks.PALLET, "货物垫板");
        translationBuilder.add(ModBlocks.PILE_OF_CARTONS, "很多纸箱");
        translationBuilder.add(ModBlocks.PORTABLE_CALCULATOR, "便携计算器");
        translationBuilder.add(ModBlocks.POST_IT_NOTE, "快捷便利贴");

        translationBuilder.add(ModBlocks.GRAYISH_WALL_LIGHT, "瓷色壁灯");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_CLOCK, "黑色简约时钟");
        translationBuilder.add(ModBlocks.BLACK_HD_TV, "清晰™黑色电视");
        translationBuilder.add(ModBlocks.BLACK_NIGHTSTAND, "瓷色床头柜");
        translationBuilder.add(ModBlocks.BLACK_BED, "瓷色大床");
        translationBuilder.add(ModBlocks.SMALL_CALLBOARD, "小型公告板");
        translationBuilder.add(ModBlocks.BLACK_AND_WHITE_SQUARE_TABLE, "纯色直角茶几");
        translationBuilder.add(ModBlocks.LOW_BLACK_AND_WHITE_SOFA, "纯色矮沙发");
        translationBuilder.add(ModBlocks.CHECKERBOARD_BOOKCASE1, "纯色棋盘式书柜 1");
        translationBuilder.add(ModBlocks.CHECKERBOARD_BOOKCASE2, "纯色棋盘式书柜 2");
        translationBuilder.add(ModBlocks.CHECKERBOARD_BOOKCASE3, "纯色棋盘式书柜 3");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_CABINET, "黑色简拼桌柜");
        translationBuilder.add(ModBlocks.BLACK_OFFICE_CHAIR, "黑色滚轮靠背椅");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_DESK_LEFT, "黑色简拼办公桌 Left");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_DESK_RIGHT, "黑色简拼办公桌 Right");

        translationBuilder.add(ModBlocks.ORANGE_WALL_LAMP, "橘色壁灯");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_CLOCK, "橘色简约时钟");
        translationBuilder.add(ModBlocks.ORANGE_HD_TV, "清晰™橘色电视");
        translationBuilder.add(ModBlocks.ORANGE_NIGHTSTAND, "橘色床头柜");
        translationBuilder.add(ModBlocks.ORANGE_BED, "橘色大床");
        translationBuilder.add(ModBlocks.SMALL_NOTICEBOARD, "小型贴示板");
        translationBuilder.add(ModBlocks.ORANGE_SQUARE_TABLE, "橘色直角茶几");
        translationBuilder.add(ModBlocks.LOW_ORANGE_SOFA, "橘色矮沙发");
        translationBuilder.add(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE1, "橘色棋盘式书柜 1");
        translationBuilder.add(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE2, "橘色棋盘式书柜 2");
        translationBuilder.add(ModBlocks.ORANGE_CHECKERBOARD_BOOKCASE3, "橘色棋盘式书柜 3");
        translationBuilder.add(ModBlocks.ORANGE_SWIVEL_CHAIR, "橘色滚轮靠背椅");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_CABINET, "橘色简拼桌柜");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_DESK_LEFT, "橘色简拼办公桌 Left");
        translationBuilder.add(ModBlocks.SIMPLE_ORANGE_DESK_RIGHT, "橘色简拼办公桌 Right");

        translationBuilder.add(ModBlocks.BROWN_BEAN_BAG_SOFA, "褐色懒人沙发");
        translationBuilder.add(ModBlocks.ECO_EXHIBITION_CABINET, "生态展览柜");
        translationBuilder.add(ModBlocks.ECO_EXHIBITION_CABINET_BASE, "生态展览柜 Base");
        translationBuilder.add(ModBlocks.FLUSH_MOUNT_RECTANGLE_CEILING_LIGHT, "内嵌宽顶灯");
        translationBuilder.add(ModBlocks.FLUSH_MOUNT_SQUARE_CEILING_LIGHT, "内嵌方顶灯");
        translationBuilder.add(ModBlocks.METALLIC_BED, "金属大床");
        translationBuilder.add(ModBlocks.POTTED_BROADLEAF_PLANT, "阔叶盆栽");
        translationBuilder.add(ModBlocks.POTTED_CONIFER_PLANT, "针叶盆栽");
        translationBuilder.add(ModBlocks.POTTED_SUCCULENT_PLANT, "厚叶盆栽");
        translationBuilder.add(ModBlocks.SMALL_SQUARE_NIGHTSTAND, "方形床头矮柜");
        translationBuilder.add(ModBlocks.SPECIMEN_DATA_BOARD, "展出标本资料板");
        translationBuilder.add(ModBlocks.WIRE_SIDE_TABLE, "筐形矮茶几");

        translationBuilder.add(ModBlocks.ANTI_EXPLOSION_TRASH_CAN, "防爆垃圾桶");
        translationBuilder.add(ModBlocks.BUILT_IN_FILE_CABINET1, "嵌壁资料柜 1");
        translationBuilder.add(ModBlocks.BUILT_IN_FILE_CABINET2, "嵌壁资料柜 2");
        translationBuilder.add(ModBlocks.BUNK_BED_IN_CABIN, "舱室组合双层床（单）");
        translationBuilder.add(ModBlocks.CABIN_FIRE_EXTINGUISHER_KIT, "舱室灭火套组");
        translationBuilder.add(ModBlocks.CABIN_FLUSH_MOUNT_PIPE, "舱室嵌顶构件");
        translationBuilder.add(ModBlocks.CONTROL_DISPLAY, "控制显示器");
        translationBuilder.add(ModBlocks.DIY_SWIVEL_CHAIR, "组合滚轮靠背椅");
        translationBuilder.add(ModBlocks.DIY_WORKBENCH_LEFT, "组合工作台 Left");
        translationBuilder.add(ModBlocks.DIY_WORKBENCH_RIGHT, "组合工作台 Right");
        translationBuilder.add(ModBlocks.GENERAL_CONSOLE, "生命循环舱总控台");
        translationBuilder.add(ModBlocks.NOTE_BOARD_IN_CABIN, "舱用记事板");

        translationBuilder.add(ModBlocks.BAR_CEILING, "吧台吊顶");
        translationBuilder.add(ModBlocks.BARSTOOL_WITH_CURVED_LEGS, "曲底高脚咖啡椅");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_COFFEE1, "饮料陈列架 Coffee 1");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_COFFEE2, "饮料陈列架 Coffee 2");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_DC, "饮料陈列架 DC");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_DRINK, "饮料陈列架 Drink");
        translationBuilder.add(ModBlocks.BEVERAGE_CABINET_EMPTY, "饮料陈列架 Empty");
        translationBuilder.add(ModBlocks.BEVERAGE_MENU, "饮料价目表");
        translationBuilder.add(ModBlocks.BOLIVARIAN_COFFEE_BEAN, "玻利瓦尔咖啡豆");
        translationBuilder.add(ModBlocks.BROWN_BOOKCASE1, "褐色跃格书架 1");
        translationBuilder.add(ModBlocks.BROWN_BOOKCASE2, "褐色跃格书架 2");
        translationBuilder.add(ModBlocks.BROWN_BOOKCASE3, "褐色跃格书架 3");
        translationBuilder.add(ModBlocks.COLUMBIAN_STREET_VIEW_PHOTO, "哥伦比亚街景照");
        translationBuilder.add(ModBlocks.DINING_CHAIR, "成对咖啡椅");
        translationBuilder.add(ModBlocks.PEDESTAL_COFFEE_TABLE, "独脚咖啡桌");
        translationBuilder.add(ModBlocks.PENDANT_LIGHT, "垂吊式顶灯");
        translationBuilder.add(ModBlocks.POTTED_LONG_LEAF_PLANT, "长叶盆栽");
        translationBuilder.add(ModBlocks.RED_BRICK_CAFE_BAR, "红砖咖啡馆吧台");
        translationBuilder.add(ModBlocks.RED_BROWN_CABINET, "红砖色储物柜");
        translationBuilder.add(ModBlocks.SOFT_CEILING_LIGHT, "柔和顶灯");

        translationBuilder.add(ModBlocks.BLACK_PEDESTAL_TABLE, "黑色独脚桌");
        translationBuilder.add(ModBlocks.BLACK_VINTAGE_CHAIR, "黑色复古椅");
        translationBuilder.add(ModBlocks.BLACK_VINTAGE_STOOL, "黑色复古凳");
        translationBuilder.add(ModBlocks.BRIGHT_WALL_LIGHT, "明亮挂灯");
        translationBuilder.add(ModBlocks.DUPLEX_WOODEN_FENCE, "复式木制墙栏");
        translationBuilder.add(ModBlocks.LOW_SANDALWOOD_MEETING_TABLE, "檀木低脚会议桌");
        translationBuilder.add(ModBlocks.SANDALWOOD_BED, "檀木大床");
        translationBuilder.add(ModBlocks.SANDALWOOD_MEETING_BOARD, "檀木会议板");
        translationBuilder.add(ModBlocks.SIMPLE_BLACK_LOUNGE_CHAIR, "黑色简装矮沙发");
        translationBuilder.add(ModBlocks.SMALL_SANDALWOOD_NIGHTSTAND, "檀木床头矮柜");

        translationBuilder.add(ModBlocks.DUPLEX_BRONZE_FENCE, "复式铜制墙栏");
        translationBuilder.add(ModBlocks.LOW_TEAK_MEETING_TABLE, "柚木低脚会议桌");
        translationBuilder.add(ModBlocks.PIANO_BLACK_VINTAGE_CHAIR, "钢琴黑复古椅");
        translationBuilder.add(ModBlocks.PIANO_BLACK_VINTAGE_STOOL, "钢琴黑复古凳");
        translationBuilder.add(ModBlocks.SIMPLE_GRAY_LOUNGE_CHAIR, "灰色简装矮沙发");
        translationBuilder.add(ModBlocks.SMALL_TEAK_NIGHTSTAND, "柚木床头矮柜");
        translationBuilder.add(ModBlocks.TEAK_BED, "柚木大床");
        translationBuilder.add(ModBlocks.TEAK_ATTENDANCE_BOARD, "柚木轮班考勤板");
        translationBuilder.add(ModBlocks.WHITE_PEDESTAL_TABLE, "白色独脚桌");

        translationBuilder.add(ModBlocks.CREATURES_REMAINS, "“生灵的躯骸”");
        translationBuilder.add(ModBlocks.FUTON_BUNK_BED_BOTTOM, "原木沙发高架床 Bottom");
        translationBuilder.add(ModBlocks.FUTON_BUNK_BED_TOP, "原木沙发高架床 Top");
        translationBuilder.add(ModBlocks.HANDMADE_WOOD_BASKET, "手编木柴篓");
        translationBuilder.add(ModBlocks.LOG_BEAM, "原木房梁");
        translationBuilder.add(ModBlocks.LOG_CABINET_BOTTOM, "原木置物柜 Bottom");
        translationBuilder.add(ModBlocks.LOG_CABINET_TOP1, "原木置物柜 Top 1");
        translationBuilder.add(ModBlocks.LOG_CABINET_TOP2, "原木置物柜 Top 2");
        translationBuilder.add(ModBlocks.LOG_DINING_CHAIR, "原木靠背椅");
        translationBuilder.add(ModBlocks.LOG_DINING_TABLE, "原木餐桌");
        translationBuilder.add(ModBlocks.ROCKING_CHAIR_WITH_CUSHION, "靠垫摇椅");
        translationBuilder.add(ModBlocks.SPRUCE_WOOD_VIOLIN, "云杉小提琴");
        translationBuilder.add(ModBlocks.VINTAGE_CEILING_FAN, "复古吊扇");
        translationBuilder.add(ModBlocks.VINTAGE_CEILING_LIGHT, "复古吊灯");

        translationBuilder.add(ModBlocks.DINING_PLATE, "餐盘");
        translationBuilder.add(ModBlocks.PIZZA_BOWL, "碗");
        translationBuilder.add(ModBlocks.PIZZA_BOX, "披萨盒");
        translationBuilder.add(ModBlocks.PIZZA_MENU1, "披萨价目表 1");
        translationBuilder.add(ModBlocks.PIZZA_MENU2, "披萨价目表 2");
        translationBuilder.add(ModBlocks.PIZZERIA_BLACK_COUNTER, "披萨店用黑色收银台");
        translationBuilder.add(ModBlocks.PIZZERIA_CUPBOARD, "披萨店用餐盘柜");
        translationBuilder.add(ModBlocks.PIZZERIA_EXIT_SIGN, "披萨店用出口指示灯");
        translationBuilder.add(ModBlocks.PIZZERIA_DINING_CHAIR, "披萨店靠背单椅");
        translationBuilder.add(ModBlocks.PIZZERIA_HIGH_STOOL, "披萨店用高脚凳");
        translationBuilder.add(ModBlocks.PIZZERIA_MOVEABLE_TABLE, "披萨店用活动餐桌");
        translationBuilder.add(ModBlocks.PIZZERIA_PLATE_RACK, "披萨店用餐盘架");
        translationBuilder.add(ModBlocks.PIZZERIA_POSTER_COLUMN, "披萨店用海报柱");
        translationBuilder.add(ModBlocks.PIZZERIA_POSTER_STAND, "披萨店用落地海报架");
        translationBuilder.add(ModBlocks.PIZZERIA_SOFT_CEILING_LIGHT, "披萨店用柔光吊灯");

        translationBuilder.add("itemGroup.logo", "Logo");
        translationBuilder.add("itemGroup.material", "基建材料");
        translationBuilder.add("itemGroup.warehouse", "货运仓库");
        translationBuilder.add("itemGroup.side_line", "边线/ 纯色/橘色 简约家居");
        translationBuilder.add("itemGroup.fantastic_bio-documentary", "幻想生物纪实");
        translationBuilder.add("itemGroup.no_12_life_cycle_cabin", "12号生命循环舱");
        translationBuilder.add("itemGroup.columbian_cafe", "哥伦比亚咖啡馆");
        translationBuilder.add("itemGroup.ldg_faux_lungmen_lounge", "近卫局/仿龙门式 休息室");
        translationBuilder.add("itemGroup.sami_countryside_villa", "萨米乡野别墅");
        translationBuilder.add("itemGroup.express_chain_pizzeria", "快餐连锁披萨店");

        translationBuilder.add("container.carton", "纸箱");
        translationBuilder.add("container.large_shelf", "大号货架");
        translationBuilder.add("container.nightstand", "床头柜");
        translationBuilder.add("container.simple_cabinet", "简拼桌柜");
        translationBuilder.add("container.checkerboard_bookcase", "棋盘式书柜");
        translationBuilder.add("container.small_square_nightstand", "方形床头矮柜");
        translationBuilder.add("container.red_brown_cabinet", "红砖色储物柜");
        translationBuilder.add("container.small_sandalwood_nightstand", "床头矮柜");
        translationBuilder.add("container.log_cabinet_bottom", "原木置物柜 Bottom");
        translationBuilder.add("container.log_cabinet_top", "原木置物柜 Top");
        translationBuilder.add("container.pizzeria_cupboard", "披萨店用餐盘柜");
    }
}
